### ISSUE TITLE
This doesn't work.

### ISSUE THREAD

**Issue by pakLebah** [pieterjongsma/swift-playgrounds-vscode#12]
Just found your extension. Installed it successfully but it failed to run. Hope it's gonna be fixed soon because I'd like to try it. Thank you.

Here's my VS Code and system:
- Version: 1.37.1
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Darwin x64 18.5.0

**Comment by pieterjongsma** [comment]
Thanks for posting an issue. Could you attach a .playground folder that doesn’t work? Even if nothing works, a simple example can be helpful. I’ll investigate as soon as I can!

**Comment by pakLebah** [comment]
Ah, sorry… my mistake. I put `import Cocoa` in my code and it failed. After I removed it, it worked. However, the output of your extension isn't exactly as the real xcode's playground. For example, `print` inside a function doesn't show the result while in xcode's playground it shows the last result.

**Comment by pieterjongsma** [comment]
Alright, I'll close this issue then.

I'm trying to get the output to mimic Xcode's, but it's hard because there is no real documentation about this. I've created a new issue for the print-statement results that you mention (#13). If you know about any other discrepancies, please let me know!
